version: '2.1'

services:
  camera-stream:
    image: ullaakut/cameradar:latest
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8554:8554"
    command: rtsp-simple-server
    restart: unless-stopped
