version: '2.1'

services:
  camera-stream:
    build: ./camera-stream
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8080:8080"
    labels:
      io.balena.features.kernel-modules: '1'
    restart: unless-stopped
